### ISSUE TITLE
并发条件下存在BUG

### ISSUE THREAD

**Issue by houbb** [houbb/opencc4j#1]
# 并发条件下存在BUG

## 修复此BUG
修复方式：
1. 仍然提供线程不安全的方式，但同时提供线程安全的方式
2. 将现有的线程不安全的方式统一修改为线程安全的方式（牺牲性能）

**Comment by himself07** [comment]
请问下并发下的结果现在是解决到什么程序了，会出现错误返回吗

**Comment by houbb** [comment]
每次使用的对象都是线程安全的（新建一个对象）
自测多线程下没有问题。 
发现问题，欢迎提 bug。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: himself07 <notifications@github.com>
发送时间: 2019年6月23日 12:01
收件人: houbb/opencc4j <opencc4j@noreply.github.com>
抄送: 叶止水 <1060732496@qq.com>, State change <state_change@noreply.github.com>
主题: 回复：[houbb/opencc4j] 并发条件下存在BUG (#1)




请问下并发下的结果现在是解决到什么程序了，会出现错误返回吗
