### ISSUE TITLE
可否支持转成香港或台湾的地区语言

### ISSUE THREAD

**Issue by skyscrapy** [houbb/opencc4j#10]
比如卸载，台湾繁体应该会翻译成 解除安装，opencc的线上版是可以的

**Comment by houbb** [comment]
可以的，周末有时间我添加下这个特性。
一开始自己主要是用大陆繁简体转换，所以这个特性没加入。

**Comment by houbb** [comment]
v1.7.0 已添加支持，并且内置了台湾地区的语言转换。香港地区的话，估计要下一个大版本。
