### ISSUE TITLE
java版本和c版本繁体字转中文结果不一致

### ISSUE THREAD

**Issue by shiwenhao** [houbb/opencc4j#11]
请教一下为啥java版本的”項鍊“的繁体字转简体字 ”项炼“ 和 c版本的不一致呢，c版本的是”项链“，这个能否修正一下，保持和c版本一致

**Comment by houbb** [comment]
原因是分词默认采用的 jieba，jieba 对于繁体分词的支持不是很友好。
后续将考虑采用 jieba 分词策略替换掉，这个周期可能相对长一点，好了这里说下。

**Comment by houbb** [comment]
v1.5.0 已修复这个问题。
