### ISSUE TITLE
判断繁简体出错

### ISSUE THREAD

**Issue by coder-bihao** [houbb/opencc4j#15]
您好，在进行汉语字的繁简体判断时出现问题。
词：寳
isSimple()  ---->true

![image](https://user-images.githubusercontent.com/49231365/81915067-ae81d000-9604-11ea-9f7a-b77096952caf.png)

这是什么原因呢？

**Comment by coder-bihao** [comment]
词：宝
isSimple(）----->true
![image](https://user-images.githubusercontent.com/49231365/81915288-f7398900-9604-11ea-8792-240857f1334e.png)


期待回复~

**Comment by houbb** [comment]
我看了下 [OpenCC](https://github.com/BYVoid/OpenCC) 提供的原始字典，确实存在这样的问题。

在繁体转简体的时候，【寳】没有作为繁体 key；简体转繁体的时候，【寳】却作为了繁体 value。

所以判断的时候会导致缺失，后续我把这个词典优化一下，尽量保证互转的一致性。

**Comment by houbb** [comment]
我用 1.5.1 自测了下面的代码，对【寶】是没问题的。

```java
String simple = "宝";
String traditional = "寶";

Assert.assertTrue(ZhConverterUtil.isSimple(simple));
Assert.assertFalse(ZhConverterUtil.isSimple(traditional));

Assert.assertTrue(ZhConverterUtil.isTraditional(traditional));
Assert.assertFalse(ZhConverterUtil.isTraditional(simple));
```

原因是 opencc 的词典【寶】和你给出的【寳】实际不是一个字。

```java
Assert.assertNotEquals("寳", "寶");
```

**Comment by coder-bihao** [comment]
谢谢回复~
又试了下，的确单个字没问题，但是如果是"支付寶"，判断这个词是简体

词：支付寶
isSample判断为真

![image](https://user-images.githubusercontent.com/49231365/82515611-373fc500-9b4b-11ea-9fa8-95d73ef55e82.png)

**Comment by houbb** [comment]
判断繁简体其实是一个辅助方法。入参应该是是一个字，或者词。

判断是否为繁体的流程：
1. 是否为繁体单个字
2. 如果超过1，则从词组中进行判断
3. 如果不是繁体的词组，则直接进行单个字，如果每一个字都是繁体，则认为是繁体。

简体则是直接取反。【支付寶】这个词不符合以上3条任何1个，所以为简体。

我不太清楚你的应用场景，方便的话可以说下。
如果很有必要，后续可以考虑引入自定义词典的特性。以前的使用经验繁体基本是固定的，所以这个特性一直没加。

**Comment by houbb** [comment]
> 谢谢回复~
> 又试了下，的确单个字没问题，但是如果是"支付寶"，判断这个词是简体
> 
> 词：支付寶
> isSample判断为真
> 
> ![image](https://user-images.githubusercontent.com/49231365/82515611-373fc500-9b4b-11ea-9fa8-95d73ef55e82.png)

以前判断繁体的第 3 步确实有些问题，我后续把分词策略调整下，保证逻辑的一致性。
预计下个版本修复这个问题。
好了我在这里回复你。
