### ISSUE TITLE
query=支付寶 isSample判断为真 与预期不符

### ISSUE THREAD

**Issue by coder-bihao** [houbb/opencc4j#16]
谢谢之前回复~
又试了下，的确单个字没问题，但是如果是"支付寶"，判断这个词是简体。
看到你的判断逻辑里，认为一个词所有字都是繁体才是繁体，但是"支付"这两个字是繁简同体，在我看来这个词"支付寶"判断为繁体是否最符合呢?
![image](https://user-images.githubusercontent.com/49231365/82516670-f6957b00-9b4d-11ea-9adf-77889ee50cf0.png)

词：支付寶
isSample判断为真

**Comment by houbb** [comment]
其实这里和方法开始的定位有些冲突，这个方法的入参定位是字或者单个词。
所以判断之后做分词会偏离定位。

比较好的方式**是先做分词，然后调用这个方法**。
比如【支付】这个是简体还是繁体？如果说繁简同体其实会增加判断的成本，而返回简体可能更符合大部分人的直觉。

你可以说下你的应用场景，或者后续引入自定义词典的功能来解决一些需要自定义的情况。

**Comment by houbb** [comment]
如果你使用 [jieba 分词](https://github.com/huaban/jieba-analysis)，结果如下：

```java
List<String> segments = Segments.huaBan().seg("支付寶");
Assert.assertEquals("[支付, 寶]", segments.toString());
```

某种角度来讲，【支付寶】不是单个字/词，这和方法的定位有偏差。
当然结巴分词支持自定义，所以繁简体的词组自定义也可作为一种解决方式。

**Comment by wnjustdoit** [comment]
对于超过一个中文字符的单词来说，是否可能定义第三种返回结果：不确定/简繁混杂

**Comment by houbb** [comment]
v1.6.2 已修复此问题。
