### ISSUE TITLE
toTraditional(char) 	返回 所有繁体字列表 問題

### ISSUE THREAD

**Issue by cj900** [houbb/opencc4j#19]
你好
我發現simpleList(String)， simpleList(String) 如果以繁體主的會出現問題
例如 "生命不息奋斗不止"; 
simpleList調用後    對繁體使用者來說，結果應該為 “奋，斗”
traditionalList調用後    對繁體使用者來說，結果應該為 “生, 命, 不, 息, 不, 止”
我想問下可否設定一個值對應繁簡地區生成不同的結果， 或者新增一個功能可以抽出繁簡相異的字詞

**Comment by houbb** [comment]
可以考虑支持，这样也灵活些。
不过最近比较忙，我周末看下能不能改一下。

**Comment by houbb** [comment]
V1.8.0 已经修复此问题。

参考：[traditionallist](https://github.com/houbb/opencc4j#%E7%B9%81%E4%BD%93%E5%88%97%E8%A1%A8-traditionallist)
