### ISSUE TITLE
JDK1.7+tomcat7启动错误,提示需要jdk1.8

### ISSUE THREAD

**Issue by wanghouqi** [houbb/opencc4j#2]
nested exception is java.lang.UnsupportedClassVersionError: com/github/houbb/paradise/common/util/StringUtil : Unsupported major.minor version 52.0 (unable to load class com.github.houbb.paradise.common.util.StringUtil)
经测试,将paradise-common-1.1.3.jar依赖移出后,可以解决如上错误.

可否去掉代码中对paradise-common-1.1.3.jar包的依赖?
1. 将StringUtil改为[commons-lang-2.5.jar]的org.apache.commons.lang.StringUtils
2. 将数组和对象的空判断改为代码的==null和size()>0
3. 将splitByAnyBlank写到自己的代码中.
	public static String[] splitByAnyBlank(String string) {
		if (StringUtils.isEmpty(string)) {
			return new String[0];
		} else {
			String pattern = "\\\s+";
			return string.split(pattern);
		}
	}

**Comment by houbb** [comment]
1. 目前 windows/mac 电脑上装的都是 jdk1.8，所以 jdk 1.7 编译会导致报错。如果需要可以直接下载，用 jdk1.7 编译使用，代码是兼容 1.7 的。
2. paradise-commons 也是为了我平时写工具方便，统一写的小工具类。

我近期有时间的话编译下 jdk1.7 版本，更新版本会说的。
