### ISSUE TITLE
第一次繁体转换会非常耗时

### ISSUE THREAD

**Issue by zzh3321** [houbb/opencc4j#21]
我这是Android项目

第一次进行繁体转换的时候，非常耗时，日志打印时间在2-3秒左右，时间根据设备配置会有差别
有没有什么办法可以提前初始化一些必要资源

`Logger.i("time__" + System.currentTimeMillis())`
`ZhConvertBootstrap.newInstance().toTraditional("生命不息，奋斗不止")`
`Logger.i("time__" + System.currentTimeMillis())`

log:
1596423927774
1596423930871

**Comment by houbb** [comment]
可以在应用启动的时候，提前做一次繁简体转换。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zzh3321 <notifications@github.com&gt;
发送时间: 2020年8月3日 11:13
收件人: houbb/opencc4j <opencc4j@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[houbb/opencc4j] 第一次繁体转换会非常耗时 (#21)





 
我这是Android项目
 
第一次进行繁体转换的时候，非常耗时，日志打印时间在2-3秒左右，时间根据设备配置会有差别
 有没有什么办法可以提前初始化一些必要资源
 
Logger.i("time__" + System.currentTimeMillis()) ZhConvertBootstrap.newInstance().toTraditional("生命不息，奋斗不止") Logger.i("time__" + System.currentTimeMillis())
 
log:
 1596423927774
 1596423930871

**Comment by houbb** [comment]
因为第一次需要进行 DFA 字典的初始化，可以在应用启动的时候，提前做一次调用。
这样后续业务正常使用的时候，性能将不受影响。

**Comment by W-qiang** [comment]
> 因为第一次需要进行 DFA 字典的初始化，可以在应用启动的时候，提前做一次调用。 这样后续业务正常使用的时候，性能将不受影响。

我这边是Android开发，提前做初始化也是不行的，字典加载会卡住主线程。我看字典都是静态代码块初始化的。能否提供异步初始化的形式呢？这样不会造成anr

**Comment by houbb** [comment]
> > 因为第一次需要进行 DFA 字典的初始化，可以在应用启动的时候，提前做一次调用。 这样后续业务正常使用的时候，性能将不受影响。
> 
> 我这边是Android开发，提前做初始化也是不行的，字典加载会卡住主线程。我看字典都是静态代码块初始化的。能否提供异步初始化的形式呢？这样不会造成anr

异步操作，我相信每一个编程语言都是有的。如果不想阻塞主线程，异步+回调自己实现下即可。这个是基础的工具包。
