### ISSUE TITLE
NoClassDefFoundError: com/github/houbb/heaven/support/instance/impl/Instances

### ISSUE THREAD

**Issue by tss0823** [houbb/opencc4j#23]
NoClassDefFoundError: com/github/houbb/heaven/support/instance/impl/Instances

**Comment by tss0823** [comment]
1.2  -1.6 都出现了这中错误，有人遇到过吗

**Comment by tss0823** [comment]
手动排除，在重新导入 heaven包就可以了

        
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>opencc4j</artifactId>
            <version>1.6.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>heaven</artifactId>
                    <groupId>com.github.houbb</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>heaven</artifactId>
            <version>0.1.118</version>
        </dependency>

**Comment by houbb** [comment]
我测试了下 v1.6.0 没有这个问题。
你这种解决方案也是可以的
