### ISSUE TITLE
床這個字簡繁都是相同的

### ISSUE THREAD

**Issue by TonyFoster** [houbb/opencc4j#26]
床這個字簡繁都是相同的
但會被判斷為簡體字，然後轉換為牀
事實上床在繁體也寫作床

**Comment by houbb** [comment]
【床】在百度百科繁简是相同的。
（1）opencc 的原文件中繁体是【牀】
（2）[简繁异字形对照](https://hanzi.unihan.com.cn/JianFanYi/detail/%E5%BA%8A) 中对应的是【牀 Unicode: 7240】
这里程序是以 opencc 的文件为准的。
