### ISSUE TITLE
关于繁体识别失误的原因和一个解决方案

### ISSUE THREAD

**Issue by bexonpak** [houbb/opencc4j#28]
https://github.com/houbb/opencc4j/blob/9ccd603beadde849faba169f7b6b590e0c73ef49/src/main/java/com/github/houbb/opencc4j/core/impl/ZhConvertBootstrap.java#L168

这里判断有个问题，必须每一个字符都是字典里有的繁体，如果一句话里有一个没有简化的字（既不是简体也不是繁体，譬如：繁，之，好……），判断就会失效。

可以参照 iOS 的逻辑来修改
如果中文语句中有一个简体别匹配，整句话就识别成简体，这时转换就转换成繁体，
如果每一个字都不在简体字体里就转成繁体。

需要实现相似功能的可以把工具类拷贝出来改改
```java
public boolean isSimple(String charOrPhrase) {
    if(StringUtil.isEmpty(charOrPhrase)) {
        return false;
    }

    final int length = charOrPhrase.length();

    if(length == 1) {
        return dataKeyContains(dataMap.stChar(), charOrPhrase);
    }

    boolean isSimplePhrase = dataKeyContains(dataMap.stPhrase(), charOrPhrase);
    if(isSimplePhrase) {
        return true;
    }

    List<String> segList = Instances.singleton(CharSegment.class).seg(charOrPhrase);
    for(String seg : segList) {
        if(isSimple(seg)) {
            return true;
        }
    }

    return false;
}
```

**Comment by houbb** [comment]
感谢提醒。

以前有这样一个 ISSUE: [query=支付寶 isSample判断为真 与预期不符](https://github.com/houbb/opencc4j/issues/16)

如果按照这种方式，会被优先确定为简体，会与上面的使用者直觉违背。
实际上还是优先繁体还是简体的问题，以后有机会调整为概率，可能使用起来更加自然。

**Comment by houbb** [comment]
v1.6.2 已改进这个问题。
