### ISSUE TITLE
输出字符串中所包含的简体字/繁体字？

### ISSUE THREAD

**Issue by houbb** [houbb/opencc4j#3]
这个功能可以拆解为两个子方法：
（1）字符串分词
（2）判断词组是否为繁体/简体
然后返回对应的词组即可。

【可能存在的问题】
当一个字繁简体同时存在时，是优先为繁体/简体，还是二者都包含？

**Comment by smartAD1** [comment]
請問在 android 裡面去做簡繁體轉換時卡住，訊息會跳出如下
Background partial concurrent mark sweep GC freed 89004(2MB) AllocSpace objects, 0(0B) LOS objects, 39% free, 8MB/14MB, paused 2.080ms total 159.819ms
要怎麼解決

**Comment by houbb** [comment]
安卓我不太清楚，不过看日志是 jvm 进入 full gc，耗时导致的。
你的使用场景是？有其他应用会导致 gc &nbsp;吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hongweizhe <notifications@github.com&gt;
发送时间: 2019年9月26日 16:18
收件人: houbb/opencc4j <opencc4j@noreply.github.com&gt;
抄送: 叶止水 <1060732496@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[houbb/opencc4j] 输出字符串中所包含的简体字/繁体字？ (#3)




請問在 android 裡面去做簡繁體轉換時卡住，訊息會跳出如下
 Background partial concurrent mark sweep GC freed 89004(2MB) AllocSpace objects, 0(0B) LOS objects, 39% free, 8MB/14MB, paused 2.080ms total 159.819ms
 要怎麼解決

**Comment by smartAD1** [comment]
> 安卓我不太清楚，不過看日誌是jvm進入full gc，耗時導致的。你的使用場景是？有其他應用會導致gc＆nbsp;嗎發自我的iPhone
> [...](#)
> ------------------ 原始邮件 ------------------ 发件人: hongweizhe <notifications@github.com&gt; 发送时间: 2019年9月26日 16:18 收件人: houbb/opencc4j <opencc4j@noreply.github.com&gt; 抄送: 叶止水 <1060732496@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[houbb/opencc4j] 输出字符串中所包含的简体字/繁体字？ (#3) 請問在 android 裡面去做簡繁體轉換時卡住，訊息會跳出如下 Background partial concurrent mark sweep GC freed 89004(2MB) AllocSpace objects, 0(0B) LOS objects, 39% free, 8MB/14MB, paused 2.080ms total 159.819ms 要怎麼解決 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
目前是在recycerview上的adapter實作繁轉簡的動作

**Comment by smartAD1** [comment]
目前是在recyclerView的adapter上實作繁轉簡的動作

**Comment by houbb** [comment]
V1.2.0 实现此功能

**Comment by smartAD1** [comment]
謝謝XD

叶止水 <notifications@github.com> 於 2019年11月5日 週二 下午8:54 寫道：
