### ISSUE TITLE
转换成不可见字符，且转换前后字符长度不一致

### ISSUE THREAD

**Issue by yanghanxy** [houbb/opencc4j#34]
**问题**
繁简转换失败，并且改变了字符长度

**版本**
```
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>opencc4j</artifactId>
            <version>1.6.0</version>
        </dependency>
```

**使用方式**
```
	String originText = "齾";
	String simpleText = ZhConverterUtil.toSimple(originText, Segments.defaults());
	System.out.println(String.format("%s, length: %d", originText, originText.length()));
	System.out.println(String.format("%s, length: %d", simpleText, simpleText.length()));
```

**输出**
```
齾, length: 1
𫜰, length: 2
```

**Comment by houbb** [comment]
估计是词库数据本身导致的，我后续做一下修复。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Han Yang ***@***.***&gt;
发送时间: 2022年1月7日 19:51
收件人: houbb/opencc4j ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/opencc4j] 转换成不可见字符，且转换前后字符长度不一致 (Issue #34)





 
问题
 繁简转换失败，并且改变了字符长度
 
版本
         <dependency&gt;             <groupId&gt;com.github.houbb</groupId&gt;             <artifactId&gt;opencc4j</artifactId&gt;             <version&gt;1.6.0</version&gt;         </dependency&gt;  
使用方式
 String originText = "齾"; String simpleText = ZhConverterUtil.toSimple(originText, Segments.defaults()); System.out.println(String.format("%s, length: %d", originText, originText.length())); System.out.println(String.format("%s, length: %d", simpleText, simpleText.length()));  
输出
 齾, length: 1 𫜰, length: 2  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanghanxy** [comment]
感谢！

另外跟您讨论下，如果转换前后字符串长度发生变化，是不是直接返回原字符串比较好？不然有些场景下会有 string offset 对不上的问题。

**Comment by houbb** [comment]
一般是程序问题才会出现不一致，大陆的繁简体转换都是一一对应的。但是台湾地区的转换可能不一样，比如 国际网络 对应 互联网 之类的。
你可以根据自己的业务做调整，工具本身不会加入这种限制。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Han Yang ***@***.***&gt;
发送时间: 2022年1月8日 13:16
收件人: houbb/opencc4j ***@***.***&gt;
抄送: 老马啸西风 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [houbb/opencc4j] 转换成不可见字符，且转换前后字符长度不一致 (Issue #34)





 
感谢！
 
另外跟您讨论下，如果转换前后字符串长度发生变化，是不是直接返回原字符串比较好？不然有些场景下会有 string offset 对不上的问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by houbb** [comment]
词库取自 opencc，我看了原来的词库就是简体对应的就是非法字符。

> [TSCharacters.txt](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TSCharacters.txt)

确实是个问题，我没具体研究过是否是这个字在简化时被移除了。

准备暂时调整为不做映射，返回本身。我做下升级，好了 ISSUE 和你说。

**Comment by houbb** [comment]
v1.7.2 已修复此问题。
