### ISSUE TITLE
判断是否繁体时错误

### ISSUE THREAD

**Issue by yezicat** [houbb/opencc4j#42]
zhConvertBootstrap.isTraditional("法國號 Fritz Kruspe")
当一段字符串中出现英文或者空格时会返回false
@Override
    public boolean isTraditional(char c) {
        if(!isChinese(c)) {
            return false;
        }

        // 繁体字符包含
        return this.dataMap.tChars().contains(c+"");
    }
debug 发现是isChinese方法返回的false

**Comment by houbb** [comment]
为了避免混乱，做了方法的确切说明，看下文档。

isTraditional 的意思是：**是否全部为繁体**

包含英文，自然不符合。

**Comment by yezicat** [comment]
用的时候眼睛花了没看到，非常感谢
